use_frameworks!
target 'MKCommonSwiftLib_Tests' do  
  pod 'MKCommonSwiftLib', :path => '../'
  
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
